### ISSUE TITLE
Tensorflow Not Found

### ISSUE THREAD

**Issue by ahsanmemon** [sander-ali/person_segmentation_background_swap#1]
Loved the notebook, easy and simple.

Also, I think you should also include a requirement file. 
Even after installing pixellib, the code still gave me an error saying that tensorflow isnt installed.

Attaching a requirement file from my computer. You can use it if you like.
[requirements.txt](https://github.com/sander-ali/person_segmentation_background_swap/files/5581330/requirements.txt)

**Comment by sander-ali** [comment]
Thanks for pointing this out. I have modified read-me file for the dependencies.
